const doctors = [
  {
    id: '1',
    name: 'Dr. John Smith',
    major: 'Cardiology',
    availability: 'Mon - Fri, 9am - 5pm',
    price: '$200 per consultation',
    picture: 'https://www.kindpng.com/picc/m/490-4909569_png-images-of-doctors-group-png-download-free.png',
  },
  {
    id: '2',
    name: 'Dr. Jane Doe',
    major: 'Pediatrics',
    availability: 'Tue - Thu, 10am - 6pm',
    price: '$150 per consultation',
    picture: 'https://thumbs.dreamstime.com/b/male-doctor-portrait-isolated-white-background-56744085.jpg',
  },
  {
    id: '3',
    name: 'Dr. Sarah Lee',
    major: 'Dermatology',
    availability: 'Mon - Wed, 9am - 3pm',
    price: '$175 per consultation',
    picture: 'https://www.shutterstock.com/image-photo/portrait-her-she-nicelooking-attractive-260nw-1729215223.jpg',
  },
  {
    id: '4',
    name: 'Dr. Michael Chen',
    major: 'Oncology',
    availability: 'Thu - Sat, 10am - 7pm',
    price: '$250 per consultation',
    picture: 'https://www.pngitem.com/pimgs/m/515-5158817_telemedicine-doctor-hd-png-download.png',
  },
  {
    id: '5',
    name: 'Dr. Emily Rodriguez',
    major: 'Psychiatry',
    availability: 'Mon - Fri, 11am - 7pm',
    price: '$180 per consultation',
    picture: 'https://thumbs.dreamstime.com/b/portrait-beautiful-asian-woman-doctor-wearing-uniform-sitting-smiling-to-teeth-white-look-camera-feel-happy-218662857.jpg',
  },
  {
    id: '6',
    name: 'Dr. David Kim',
    major: 'Orthopedics',
    availability: 'Mon - Thu, 8am - 4pm',
    price: '$225 per consultation',
    picture: 'https://hips.hearstapps.com/hmg-prod/images/portrait-of-a-happy-young-doctor-in-his-clinic-royalty-free-image-1661432441.jpg',
  },
  {
    id: '7',
    name: 'Dr. Rachel Wong',
    major: 'Gynecology',
    availability: 'Mon - Fri, 9am - 5pm',
    price: '$190 per consultation',
    picture: 'https://st2.depositphotos.com/1013513/12104/i/950/depositphotos_121040752-stock-photo-smiling-female-doctors-working-in.jpg',
  },
  {
    id: '8',
    name: 'Dr. William Park',
    major: 'Neurology',
    availability: 'Wed - Sun, 11am - 7pm',
    price: '$275 per consultation',
    picture: 'https://t3.ftcdn.net/jpg/02/95/51/80/360_F_295518052_aO5d9CqRhPnjlNDTRDjKLZHNftqfsxzI.jpg',
  },
  {
    id: '9',
    name: 'Dr. Jessica Nguyen',
    major: 'Allergy and Immunology',
    availability: 'Tue - Thu, 8am - 4pm',
    price: '$160 per consultation',
    picture: 'https://static.vecteezy.com/system/resources/previews/005/128/689/large_2x/beautiful-woman-doctor-with-hijab-portrait-on-white-background-free-photo.jpg',
  },
];

export default doctors;
